CREATE TABLE ApplicationUser (ID VARCHAR(255) NOT NULL, CREATEDBYID VARCHAR(255), CREATEDON DATE, DELETEDBYID VARCHAR(255), DELETEDON DATE, EMAIL VARCHAR(50) NOT NULL, PASSWORD VARCHAR(64) NOT NULL, UPDATEDBYID VARCHAR(255), UPDATEDON DATE, PRIMARY KEY (ID));
CREATE TABLE MEAL (ID VARCHAR(255) NOT NULL, CALORIES INTEGER, CARBS INTEGER, CREATEDBYID VARCHAR(255), CREATEDON DATE, DELETEDBYID VARCHAR(255), DELETEDON DATE, FATS INTEGER, MEALDATE DATE, MEALWEIGHT INTEGER, PROTEINS INTEGER, UPDATEDBYID VARCHAR(255), UPDATEDON DATE, ApplicationUserId VARCHAR(255) NOT NULL, MealDataId VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE MEALDATA (ID VARCHAR(255) NOT NULL, CALORIESPER100GRAMS INTEGER, CARBSPER100GRAMS INTEGER, FATSPER100GRAMS INTEGER, NAME VARCHAR(255), PROTEINSPER100GRAMS INTEGER, PRIMARY KEY (ID));
ALTER TABLE ApplicationUser ADD CONSTRAINT UNQ_ApplicationUser_0 UNIQUE (Email);
ALTER TABLE MEAL ADD CONSTRAINT FK_MEAL_ApplicationUserId FOREIGN KEY (ApplicationUserId) REFERENCES ApplicationUser (ID);
ALTER TABLE MEAL ADD CONSTRAINT FK_MEAL_MealDataId FOREIGN KEY (MealDataId) REFERENCES MEALDATA (ID);
